### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by pujianjun** [mmzou/geektime-dl#29]
一开始都可以登录并下载成功视频课的，可突然下载一半就下载不了了，试了很多次重启电脑也不行了，执行geektime-dl 190报错：
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/mmzou/geektime-dl/downloader.Download(0x17bb2, 0x11f45f60, 0x11, 0x568392, 0x6, 0x1, 0x1200a240, 0x0, 0x0, 0x0, ...)
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/downloader/downloader.go:43 +0x8dd
github.com/mmzou/geektime-dl/cli/cmds.downloadAction(0x11c24420, 0x11c0fa00, 0x0)
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/cli/cmds/download.go:72 +0x57a
github.com/urfave/cli.HandleAction(0x4c3d00, 0x592594, 0x11c24420, 0x11c24420, 0x0)
	/home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0xe3
github.com/urfave/cli.Command.Run(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x4a4
github.com/mmzou/geektime-dl/cli/cmds.DefaultAction(0x11c24370, 0x0, 0x0)
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/cli/cmds/cmds.go:86 +0xac
github.com/urfave/cli.HandleAction(0x4c3d00, 0x592584, 0x11c24370, 0x0, 0x0)
	/home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0xe3
github.com/urfave/cli.(*App).Run(0x11c01420, 0x11c0c040, 0x2, 0x2, 0x0, 0x0)
	/home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:288 +0x575
main.main()
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/main.go:30 +0x3f0

运行环境：macos 10.14.5 (18F132)、geektime-dl version dev
谢谢！

**Comment by BruceZhang1993** [comment]
same here. 
OS: Arch Linux
latest release

**Comment by andyyxw** [comment]
同样的情况，现在好像课程下载不了了
<img width="905" alt="Xnip2020-06-27_20-29-38" src="https://user-images.githubusercontent.com/41931722/85922361-34a45e00-b8b5-11ea-9b40-493418edad2c.png">

**Comment by freecow** [comment]
同样问题，在macos上，下载不了了

**Comment by hcliu987** [comment]
看样子都是这样的

**Comment by Rundong-Li** [comment]
是的，现在没法用了...

**Comment by FmouseLi** [comment]
对获取m3u8地址的请求进行了加密，获取不到了。

**Comment by FmouseLi** [comment]
试过使用正确的m3u8地址下载到ts文件之后，MergeToMP4的时候失败，应该是对内容进行了加密，读取的时候需要先解密吧。
