### ISSUE TITLE
下载新的购买视频的时候 报这个错误

### ISSUE THREAD

**Issue by UIT2016wanghui** [mmzou/geektime-dl#32]
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/mmzou/geektime-dl/downloader.Download(0x3e3ac, 0xc000296c60, 0x20, 0x16a9034, 0x6, 0x1, 0xc000293230, 0x0, 0x0, 0x0, ...)
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/downloader/downloader.go:43 +0xb3e
github.com/mmzou/geektime-dl/cli/cmds.downloadAction(0xc00022e160, 0x0, 0xc000206b10)
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/cli/cmds/download.go:72 +0x6f5
github.com/urfave/cli.HandleAction(0x15d7800, 0x16d2080, 0xc00022e160, 0xc00022e160, 0x0)
	/home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x11a
github.com/urfave/cli.Command.Run(0x16a6698, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x16a6698, 0x0, 0x16a6698, ...)
	/home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x57a
github.com/mmzou/geektime-dl/cli/cmds.DefaultAction(0xc00022e000, 0x0, 0x0)
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/cli/cmds/cmds.go:86 +0x104
github.com/urfave/cli.HandleAction(0x15d7800, 0x16d2060, 0xc00022e000, 0x0, 0x0)
	/home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x11a
github.com/urfave/cli.(*App).Run(0xc000218380, 0xc000098180, 0x3, 0x3, 0x0, 0x0)
	/home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:288 +0x649
main.main()
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/main.go:30 +0x4c7
➜  Downloads

**Comment by cmgook** [comment]
专栏可以下载，但是下载视频课程失败，同上

**Comment by musichunter** [comment]
和1楼是同样的错误

**Comment by zgblog** [comment]
一样的问题

**Comment by qfeng3168** [comment]
一样的问题
