### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by dqylyln** [mmzou/geektime-dl#34]
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/mmzou/geektime-dl/downloader.Download(0x2bd2f, 0xc0002ead00, 0x11, 0xaa0069, 0x6, 0x1, 0xc000288480, 0x0, 0x0, 0x0, ...)
        /home/miaoke/go/src/github.com/mmzou/geektime-dl/downloader/downloader.go:43 +0xb45
github.com/mmzou/geektime-dl/cli/cmds.downloadAction(0xc0000f09a0, 0x0, 0xc0001c0e10)
        /home/miaoke/go/src/github.com/mmzou/geektime-dl/cli/cmds/download.go:72 +0x6fc
github.com/urfave/cli.HandleAction(0x9d3280, 0xaca0e8, 0xc0000f09a0, 0xc0000f09a0, 0x0)
        /home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x121
github.com/urfave/cli.Command.Run(0xa9d678, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa9d678, 0x0, 0xa9d678, ...)
        /home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x581
github.com/mmzou/geektime-dl/cli/cmds.DefaultAction(0xc0000f0840, 0x0, 0x0)
        /home/miaoke/go/src/github.com/mmzou/geektime-dl/cli/cmds/cmds.go:86 +0x10b
github.com/urfave/cli.HandleAction(0x9d3280, 0xaca0c8, 0xc0000f0840, 0x0, 0x0)
        /home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x121
github.com/urfave/cli.(*App).Run(0xc00011c540, 0xc000096440, 0x2, 0x2, 0x0, 0x0)
        /home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:288 +0x650
main.main()
        /home/miaoke/go/src/github.com/mmzou/geektime-dl/main.go:30 +0x4ce

**Comment by Rundong-Li** [comment]
这个下载器现在用不了了...
