### ISSUE TITLE
Mac 使用的geektime-dl_0.2.2_macOS_64-bit版本下载视频报错

### ISSUE THREAD

**Issue by xuhj-code** [mmzou/geektime-dl#47]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x157a27b]

goroutine 60 [running]:
github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData.func1(0xc0002a4a50, 0xc0000b9040, 0xc00019e0f0)
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/cli/cmds/download.go:213 +0xcb
created by github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/cli/cmds/download.go:207 +0x772

**Comment by zhengyifanvp** [comment]
我是windows我也是这个问题

**Comment by zhengyifanvp** [comment]
@xuhj-code 解决了吗

**Comment by free-kai** [comment]
我也是，还有救嘛

**Comment by GhostedProgramer** [comment]
@xuhj-code 有解决方案了不?

**Comment by dalewang1995** [comment]
大佬们，有解决方案吗？
