### ISSUE TITLE
下载课程时报内存溢出

### ISSUE THREAD

**Issue by liberjiang** [mmzou/geektime-dl#50]
![image](https://user-images.githubusercontent.com/30001231/100064100-0aa79580-2e6d-11eb-9a2a-219b180052f1.png)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1c pc=0x53b2e2]

goroutine 15 [running]:
github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData.func1(0x121b7648, 0x121c82a0, 0x12195a80)
        C:/Users/EDZ/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20200623030700-f0123abd709d/cli/cmds/download.go:213 +0xb2
created by github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData
        C:/Users/EDZ/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20200623030700-f0123abd709d/cli/cmds/download.go:207 +0x5a8

**Comment by chengxiao** [comment]
同样的问题
机器
MBP M1  16G
已安装ffmpeg

**Comment by c0ding** [comment]
同样的问题
机器
MBP M1 16G
已安装ffmpeg

![image](https://user-images.githubusercontent.com/13250462/104708146-4584c600-5758-11eb-9c82-30f8f8073161.png)

**Comment by bluemiaomiao** [comment]
同样的问题：

```
geektime-dl git:(master) ✗ ./geektime-dl 190
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x15f8a4e]

goroutine 13 [running]:
github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData.func1(0xc0002314a0, 0xc00035cb40, 0xc0001d6bd0)
	/Users/xujunjie/Downloads/geektime-dl/cli/cmds/download.go:213 +0xce
created by github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData
	/Users/xujunjie/Downloads/geektime-dl/cli/cmds/download.go:207 +0x7a8
```

ffmpeg和chrome已安装，MBP 2015 x86_64

**Comment by bluemiaomiao** [comment]
Windows 10也是这样：

```
C:\Users\xujunjie\geektime-dl>geektime-dl.exe 190
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0xb1187a]

goroutine 33 [running]:
github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData.func1(0xc0003a80f0, 0xc000293220, 0xc00029faa0)
        C:/Users/xujunjie/geektime-dl/cli/cmds/download.go:213 +0xda
created by github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData
        C:/Users/xujunjie/geektime-dl/cli/cmds/download.go:207 +0x7a8

C:\Users\xujunjie\geektime-dl>geektime-dl.exe --debug 190
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0xb1187a]

goroutine 35 [running]:
github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData.func1(0xc0003a29c0, 0xc0002b16d0, 0xc0002c5e00)
        C:/Users/xujunjie/geektime-dl/cli/cmds/download.go:213 +0xda
created by github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData
        C:/Users/xujunjie/geektime-dl/cli/cmds/download.go:207 +0x7a8
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0xb1187a]

goroutine 27 [running]:
github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData.func1(0xc0003a29c0, 0xc0002b1450, 0xc0002c5e00)
        C:/Users/xujunjie/geektime-dl/cli/cmds/download.go:213 +0xda
created by github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData
        C:/Users/xujunjie/geektime-dl/cli/cmds/download.go:207 +0x7a8
```

下载视频的时候。

**Comment by jsabook** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x9c0f62]

goroutine 64 [running]:
github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData.func1(0xc000210ac0, 0xc0000c0370, 0xc00007c750)
        /Users/weiyongsheng/go/src/github.com/mmzou/geektime-dl/cli/cmds/download.go:213 +0xd2
created by github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData
        /Users/weiyongsheng/go/src/github.com/mmzou/geektime-dl/cli/cmds/download.go:207 +0x779
