### ISSUE TITLE
下载视频课程报错

### ISSUE THREAD

**Issue by feilang864** [mmzou/geektime-dl#55]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x15f8a8e]

goroutine 31 [running]:
github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData.func1(0xc00022b730, 0xc000302320, 0xc0004a4000)
	/Users/jesse/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20210121052731-54987d7a4e6b/cli/cmds/download.go:213 +0xce
created by github.com/mmzou/geektime-dl/cli/cmds.extractVideoDownloadData
	/Users/jesse/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20210121052731-54987d7a4e6b/cli/cmds/download.go:207 +0x7a8

**Comment by abbycin** [comment]
这边也是这个问题，看了下代码，是因为 [https://github.com/mmzou/geektime-dl/blob/54987d7a4e6b476ad5b4ea735c6c2ec520711d32/service/requester.go#L65](https://github.com/mmzou/geektime-dl/blob/54987d7a4e6b476ad5b4ea735c6c2ec520711d32/service/requester.go#L65)
这个地址连接超时了，然后这里没处理错误导致的 [https://github.com/mmzou/geektime-dl/blob/54987d7a4e6b476ad5b4ea735c6c2ec520711d32/cli/cmds/download.go#L212](https://github.com/mmzou/geektime-dl/blob/54987d7a4e6b476ad5b4ea735c6c2ec520711d32/cli/cmds/download.go#L212)

但是，不知道这个地址是怎么来的，没法改。。 @mmzou
