### ISSUE TITLE
安装完执行报错

### ISSUE THREAD

**Issue by zzyxka** [mmzou/geektime-dl#8]
![image](https://user-images.githubusercontent.com/26628346/81277346-df9f5500-9086-11ea-8170-673d1e94df13.png)

**Comment by zzyxka** [comment]
```
$ ./geektime-dl column
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x14cf1d4]

goroutine 1 [running]:
github.com/mmzou/geektime-dl/config.(*Geektime).Service(...)
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/config/geek.go:28
github.com/mmzou/geektime-dl/config.(*ConfigsData).ActiveUserService(0xc0001d5800, 0x1bf8840)
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/config/config.go:223 +0x44
github.com/mmzou/geektime-dl/cli/application.getService(...)
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/cli/application/func.go:9
github.com/mmzou/geektime-dl/cli/application.Columns(0x0, 0xc0000a4638, 0x178f980, 0xc00028f540, 0x0)
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/cli/application/course.go:9 +0x2d
github.com/mmzou/geektime-dl/cli/cmds.columnAction(0xc0000bc160, 0x0, 0xc00009aa70)
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/cli/cmds/course.go:33 +0x22
github.com/urfave/cli.HandleAction(0x15d76c0, 0x16d1f38, 0xc0000bc160, 0xc0000bc160, 0x0)
	/home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x11a
github.com/urfave/cli.Command.Run(0x16a8564, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x16b3208, 0x12, 0xc000098640, ...)
	/home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x57a
github.com/urfave/cli.(*App).Run(0xc0000ac380, 0xc00000c080, 0x2, 0x2, 0x0, 0x0)
	/home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 +0x7c7
main.main()
	/home/miaoke/go/src/github.com/mmzou/geektime-dl/main.go:30 +0x4c7
```
