### ISSUE TITLE
login 报错是什么原因？

### ISSUE THREAD

**Issue by ZJRui** [mmzou/geektime-dl#86]
dz0400847@DZ0400847 bin % ./geektime-dl login --phone   --password 

unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x1063eff]

goroutine 1 [running]:
runtime.throw({0x1689849?, 0xd0?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc000258c40 sp=0xc000258c10 pc=0x10361dd
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:842 +0x2c5 fp=0xc000258c90 sp=0xc000258c40 pc=0x104bc05
aeshashbody()
	/usr/local/go/src/runtime/asm_amd64.s:1366 +0x39f fp=0xc000258c98 sp=0xc000258c90 pc=0x1063eff
runtime.mapiternext(0xc000326080)
	/usr/local/go/src/runtime/map.go:936 +0x2eb fp=0xc000258d08 sp=0xc000258c98 pc=0x10112ab
runtime.mapiterinit(0xc0003200d0?, 0x100c000320070?, 0xc00031c050?)
	/usr/local/go/src/runtime/map.go:863 +0x236 fp=0xc000258d28 sp=0xc000258d08 pc=0x1010f76
reflect.mapiterinit(0xc000258dc8?, 0x100e9ff?, 0x0?)
	/usr/local/go/src/runtime/map.go:1375 +0x19 fp=0xc000258d50 sp=0xc000258d28 pc=0x10606b9
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
	/Users/dz0400847/go/pkg/mod/github.com/modern-go/reflect2@v0.0.0-20180701023420-4b7aa43c6742/unsafe_map.go:112
github.com/json-iterator/go.(*mapEncoder).Encode(0xc000312270, 0xc00031c058, 0xc000334000)
	/Users/dz0400847/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_map.go:257 +0x229 fp=0xc000258e00 sp=0xc000258d50 pc=0x14bf469
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0003200b0, 0xc000312120, 0xc000326080?)
	/Users/dz0400847/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:219 +0x82 fp=0xc000258e38 sp=0xc000258e00 pc=0x14b8142
github.com/json-iterator/go.(*Stream).WriteVal(0xc000334000, {0x15dd900, 0xc000312120})
	/Users/dz0400847/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:98 +0x166 fp=0xc000258ea8 sp=0xc000258e38 pc=0x14b7466
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc0000d8b40, {0x15dd900, 0xc000312120})
	/Users/dz0400847/go/pkg/mod/github.com/json-iterator/go@v1.1.9/config.go:299 +0xc9 fp=0xc000258f40 sp=0xc000258ea8 pc=0x14ae6e9
github.com/json-iterator/go.Marshal(...)
	/Users/dz0400847/go/pkg/mod/github.com/json-iterator/go@v1.1.9/adapter.go:34
github.com/mmzou/geektime-dl/requester.(*HTTPClient).Req(0xc0000fb2c0, {0x1688c86, 0x4}, {0x16ace49, 0x31}, {0x15dd900, 0xc000312120?}, 0xc0002591c0)
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/requester/fetch.go:85 +0x326 fp=0xc0002590a8 sp=0xc000258f40 pc=0x14dc146
github.com/mmzou/geektime-dl/requester.(*HTTPClient).Fetch(0x15dd900?, {0x1688c86?, 0x168e1f6?}, {0x16ace49?, 0x0?}, {0x15dd900?, 0xc000312120?}, 0xc0002591d0?)
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/requester/fetch.go:126 +0x74 fp=0xc000259150 sp=0xc0002590a8 pc=0x14dc654
github.com/mmzou/geektime-dl/login.(*Client).Login(0xc0000c0398, {0x7ffeefbffa2c, 0xb}, {0x7ffeefbffa43, 0x8})
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/login/login_client.go:76 +0x405 fp=0xc000259310 sp=0xc000259150 pc=0x15016e5
github.com/mmzou/geektime-dl/cli/application.Login({0x7ffeefbffa2c, 0xb}, {0x7ffeefbffa43, 0x8})
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/cli/application/login.go:12 +0x4a fp=0xc000259358 sp=0xc000259310 pc=0x15023ca
github.com/mmzou/geektime-dl/cli/cmds.loginAction(0xc00018a6e0?)
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/cli/cmds/login.go:109 +0x6d fp=0xc0002593c0 sp=0xc000259358 pc=0x15783ed
github.com/urfave/cli.HandleAction({0x15c2f20?, 0x16cf4c8?}, 0x5?)
	/Users/dz0400847/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x50 fp=0xc0002593d8 sp=0xc0002593c0 pc=0x1550850
github.com/urfave/cli.Command.Run({{0x16899cf, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1691a5d, 0xe}, {0xc0000dea40, ...}, ...}, ...)
	/Users/dz0400847/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x65b fp=0xc0002595b8 sp=0xc0002593d8 pc=0x15516bb
github.com/urfave/cli.(*App).Run(0xc000278380, {0xc0000c2120, 0x6, 0x6})
	/Users/dz0400847/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 +0x927 fp=0xc000259b90 sp=0xc0002595b8 pc=0x154df07
main.main()
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/main.go:30 +0x49f fp=0xc000259f80 sp=0xc000259b90 pc=0x157913f
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc000259fe0 sp=0xc000259f80 pc=0x10389f2
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000259fe8 sp=0xc000259fe0 pc=0x1066b21

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00006cfb0 sp=0xc00006cf90 pc=0x1038db6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:302 +0xad fp=0xc00006cfe0 sp=0xc00006cfb0 pc=0x1038c4d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00006cfe8 sp=0xc00006cfe0 pc=0x1066b21
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00006d790 sp=0xc00006d770 pc=0x1038db6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00006d7c8 sp=0xc00006d790 pc=0x1025f6e
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc00006d7e0 sp=0xc00006d7c8 pc=0x101ac26
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00006d7e8 sp=0xc00006d7e0 pc=0x1066b21
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00007e000?, 0x17703b8?, 0x1?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00006df70 sp=0xc00006df50 pc=0x1038db6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x1b7afc0)
	/usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc00006dfa0 sp=0xc00006df70 pc=0x1024013
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc00006dfc8 sp=0xc00006dfa0 pc=0x10245e5
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc00006dfe0 sp=0xc00006dfc8 pc=0x101abc6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00006dfe8 sp=0xc00006dfe0 pc=0x1066b21
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x1b7b9e0?, 0xc00009a4e0?, 0x0?, 0x0?, 0xc00006c770?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00006c628 sp=0xc00006c608 pc=0x1038db6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:180 +0x10f fp=0xc00006c7e0 sp=0xc00006c628 pc=0x1019d2f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00006c7e8 sp=0xc00006c7e0 pc=0x1066b21
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:157 +0x45

goroutine 25 [IO wait]:
runtime.gopark(0xa?, 0xc00028c000?, 0x0?, 0x10?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000304620 sp=0xc000304600 pc=0x1038db6
runtime.netpollblock(0x10ac7e9?, 0x11a?, 0x0?)
	/usr/local/go/src/runtime/netpoll.go:526 +0xf7 fp=0xc000304658 sp=0xc000304620 pc=0x1032277
internal/poll.runtime_pollWait(0x2d30b58, 0x72)
	/usr/local/go/src/runtime/netpoll.go:305 +0x89 fp=0xc000304678 sp=0xc000304658 pc=0x1060f69
internal/poll.(*pollDesc).wait(0xc00023d780?, 0xc00028c000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc0003046a0 sp=0xc000304678 pc=0x10c5832
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00023d780, {0xc00028c000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a fp=0xc000304720 sp=0xc0003046a0 pc=0x10c6b9a
net.(*netFD).Read(0xc00023d780, {0xc00028c000?, 0xc0000ed120?, 0xc00028c00d?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29 fp=0xc000304768 sp=0xc000304720 pc=0x11ce7e9
net.(*conn).Read(0xc0000c03d0, {0xc00028c000?, 0x0?, 0x0?})
	/usr/local/go/src/net/net.go:183 +0x45 fp=0xc0003047b0 sp=0xc000304768 pc=0x11dc605
crypto/tls.(*atLeastReader).Read(0xc00030a018, {0xc00028c000?, 0x0?, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:787 +0x3d fp=0xc0003047f8 sp=0xc0003047b0 pc=0x1214ddd
bytes.(*Buffer).ReadFrom(0xc00027a978, {0x1771d00, 0xc00030a018})
	/usr/local/go/src/bytes/buffer.go:202 +0x98 fp=0xc000304850 sp=0xc0003047f8 pc=0x10f7ef8
crypto/tls.(*Conn).readFromUntil(0xc00027a700, {0x2d35648?, 0xc0000c03d0}, 0xc0003048e0?)
	/usr/local/go/src/crypto/tls/conn.go:809 +0xe5 fp=0xc000304890 sp=0xc000304850 pc=0x1214fc5
crypto/tls.(*Conn).readRecordOrCCS(0xc00027a700, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:616 +0x116 fp=0xc000304c18 sp=0xc000304890 pc=0x1212416
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0xc00027a700, {0xc00028d000, 0x1000, 0x1?})
	/usr/local/go/src/crypto/tls/conn.go:1287 +0x16f fp=0xc000304c88 sp=0xc000304c18 pc=0x121806f
net/http.(*persistConn).Read(0xc0002210e0, {0xc00028d000?, 0x1048de0?, 0xc000304ec8?})
	/usr/local/go/src/net/http/transport.go:1929 +0x4e fp=0xc000304ce8 sp=0xc000304c88 pc=0x12a3e4e
bufio.(*Reader).fill(0xc000283320)
	/usr/local/go/src/bufio/bufio.go:106 +0xff fp=0xc000304d20 sp=0xc000304ce8 pc=0x123e19f
bufio.(*Reader).Peek(0xc000283320, 0x1)
	/usr/local/go/src/bufio/bufio.go:144 +0x5d fp=0xc000304d40 sp=0xc000304d20 pc=0x123e2fd
net/http.(*persistConn).readLoop(0xc0002210e0)
	/usr/local/go/src/net/http/transport.go:2093 +0x1ac fp=0xc000304fc8 sp=0xc000304d40 pc=0x12a4c6c
net/http.(*Transport).dialConn.func5()
	/usr/local/go/src/net/http/transport.go:1751 +0x26 fp=0xc000304fe0 sp=0xc000304fc8 pc=0x12a3446
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000304fe8 sp=0xc000304fe0 pc=0x1066b21
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1751 +0x173e

goroutine 26 [select]:
runtime.gopark(0xc000080f90?, 0x2?, 0xd8?, 0xd?, 0xc000080f24?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000080d90 sp=0xc000080d70 pc=0x1038db6
runtime.selectgo(0xc000080f90, 0xc000080f20, 0xc0000fb680?, 0x0, 0xc0002a0300?, 0x1)
	/usr/local/go/src/runtime/select.go:328 +0x7bc fp=0xc000080ed0 sp=0xc000080d90 pc=0x104805c
net/http.(*persistConn).writeLoop(0xc0002210e0)
	/usr/local/go/src/net/http/transport.go:2392 +0xf5 fp=0xc000080fc8 sp=0xc000080ed0 pc=0x12a68f5
net/http.(*Transport).dialConn.func6()
	/usr/local/go/src/net/http/transport.go:1752 +0x26 fp=0xc000080fe0 sp=0xc000080fc8 pc=0x12a33e6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000080fe8 sp=0xc000080fe0 pc=0x1066b21
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1752 +0x1791
dz0400847@DZ0400847 bin % ./geektime-dl column
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x1063eff]

goroutine 1 [running]:
runtime.throw({0x1689849?, 0xd0?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc00023ebe0 sp=0xc00023ebb0 pc=0x10361dd
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:842 +0x2c5 fp=0xc00023ec30 sp=0xc00023ebe0 pc=0x104bc05
aeshashbody()
	/usr/local/go/src/runtime/asm_amd64.s:1366 +0x39f fp=0xc00023ec38 sp=0xc00023ec30 pc=0x1063eff
runtime.mapiternext(0xc000163180)
	/usr/local/go/src/runtime/map.go:936 +0x2eb fp=0xc00023eca8 sp=0xc00023ec38 pc=0x10112ab
runtime.mapiterinit(0xc000252ff0?, 0x100c000252f80?, 0xc0001283c8?)
	/usr/local/go/src/runtime/map.go:863 +0x236 fp=0xc00023ecc8 sp=0xc00023eca8 pc=0x1010f76
reflect.mapiterinit(0xc00023ed68?, 0x100e9ff?, 0x0?)
	/usr/local/go/src/runtime/map.go:1375 +0x19 fp=0xc00023ecf0 sp=0xc00023ecc8 pc=0x10606b9
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
	/Users/dz0400847/go/pkg/mod/github.com/modern-go/reflect2@v0.0.0-20180701023420-4b7aa43c6742/unsafe_map.go:112
github.com/json-iterator/go.(*mapEncoder).Encode(0xc000265020, 0xc0001283d0, 0xc00019bd40)
	/Users/dz0400847/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_map.go:257 +0x229 fp=0xc00023eda0 sp=0xc00023ecf0 pc=0x14bf469
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc000252fd0, 0xc000264ed0, 0xc000163180?)
	/Users/dz0400847/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:219 +0x82 fp=0xc00023edd8 sp=0xc00023eda0 pc=0x14b8142
github.com/json-iterator/go.(*Stream).WriteVal(0xc00019bd40, {0x15dd480, 0xc000264ed0})
	/Users/dz0400847/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:98 +0x166 fp=0xc00023ee48 sp=0xc00023edd8 pc=0x14b7466
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc000142b40, {0x15dd480, 0xc000264ed0})
	/Users/dz0400847/go/pkg/mod/github.com/json-iterator/go@v1.1.9/config.go:299 +0xc9 fp=0xc00023eee0 sp=0xc00023ee48 pc=0x14ae6e9
github.com/json-iterator/go.Marshal(...)
	/Users/dz0400847/go/pkg/mod/github.com/json-iterator/go@v1.1.9/adapter.go:34
github.com/mmzou/geektime-dl/requester.(*HTTPClient).Req(0xc000162d00, {0x1688c86, 0x4}, {0x16ac162, 0x2f}, {0x15dd480, 0xc000264ed0?}, 0xc00023f090)
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/requester/fetch.go:85 +0x326 fp=0xc00023f048 sp=0xc00023eee0 pc=0x14dc146
github.com/mmzou/geektime-dl/service.(*Service).requestCourses(0xc000128388, 0x1)
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/service/requester.go:22 +0x12c fp=0xc00023f1e0 sp=0xc00023f048 pc=0x14e0c4c
github.com/mmzou/geektime-dl/service.(*Service).courses(0x0?, 0x0?)
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/service/course.go:27 +0x65 fp=0xc00023f340 sp=0xc00023f1e0 pc=0x14df3a5
github.com/mmzou/geektime-dl/service.(*Service).getCourses(0x15dcb80?, 0x1779310?)
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/service/course.go:17 +0x1e fp=0xc00023f378 sp=0xc00023f340 pc=0x14df2de
github.com/mmzou/geektime-dl/service.(*Service).Columns(...)
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/service/course.go:7
github.com/mmzou/geektime-dl/cli/application.Columns()
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/cli/application/course.go:11 +0x2f fp=0xc00023f398 sp=0xc00023f378 pc=0x150200f
github.com/mmzou/geektime-dl/cli/cmds.columnAction(0xc000172840?)
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/cli/cmds/course.go:33 +0x19 fp=0xc00023f3c0 sp=0xc00023f398 pc=0x1575b39
github.com/urfave/cli.HandleAction({0x15c2f20?, 0x16cf4a8?}, 0x6?)
	/Users/dz0400847/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x50 fp=0xc00023f3d8 sp=0xc00023f3c0 pc=0x1550850
github.com/urfave/cli.Command.Run({{0x168a56b, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1696598, 0x12}, {0xc000130468, ...}, ...}, ...)
	/Users/dz0400847/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x65b fp=0xc00023f5b8 sp=0xc00023f3d8 pc=0x15516bb
github.com/urfave/cli.(*App).Run(0xc000260380, {0xc000132000, 0x2, 0x2})
	/Users/dz0400847/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 +0x927 fp=0xc00023fb90 sp=0xc00023f5b8 pc=0x154df07
main.main()
	/Users/dz0400847/go/pkg/mod/github.com/mmzou/geektime-dl@v0.0.0-20220523030627-847adf77fe85/main.go:30 +0x49f fp=0xc00023ff80 sp=0xc00023fb90 pc=0x157913f
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc00023ffe0 sp=0xc00023ff80 pc=0x10389f2
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00023ffe8 sp=0xc00023ffe0 pc=0x1066b21

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00006cfb0 sp=0xc00006cf90 pc=0x1038db6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:302 +0xad fp=0xc00006cfe0 sp=0xc00006cfb0 pc=0x1038c4d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00006cfe8 sp=0xc00006cfe0 pc=0x1066b21
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00006d790 sp=0xc00006d770 pc=0x1038db6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00006d7c8 sp=0xc00006d790 pc=0x1025f6e
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc00006d7e0 sp=0xc00006d7c8 pc=0x101ac26
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00006d7e8 sp=0xc00006d7e0 pc=0x1066b21
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00007c000?, 0x17703b8?, 0x1?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00006df70 sp=0xc00006df50 pc=0x1038db6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x1b7afc0)
	/usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc00006dfa0 sp=0xc00006df70 pc=0x1024013
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc00006dfc8 sp=0xc00006dfa0 pc=0x10245e5
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc00006dfe0 sp=0xc00006dfc8 pc=0x101abc6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00006dfe8 sp=0xc00006dfe0 pc=0x1066b21
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x1b7b9e0?, 0xc0001024e0?, 0x0?, 0x0?, 0xc00006c770?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00006c628 sp=0xc00006c608 pc=0x1038db6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:180 +0x10f fp=0xc00006c7e0 sp=0xc00006c628 pc=0x1019d2f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00006c7e8 sp=0xc00006c7e0 pc=0x1066b21
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:157 +0x45

**Comment by anonymousch** [comment]
go get -u && go build
